export const GET_MY_FILES = 'GET_MY_FILES';
export const SET_MY_FILES = 'SET_MY_FILES';

export const GET_MY_FILES_BY_ID = 'GET_MY_FILES_BY_ID';
export const SET_MY_FILES_BY_ID = 'SET_MY_FILES_BY_ID';

export const GET_CREATE_FOLDER = 'GET_CREATE_FOLDER';
export const SET_CREATE_FOLDER = 'SET_CREATE_FOLDER';

export const GET_CREATE_FILES = 'GET_CREATE_FILES';
export const SET_CREATE_FILES = 'SET_CREATE_FILES';


export const GET_DELETE_FOLDER = 'GET_DELETE_FOLDER';
export const SET_DELETE_FOLDER = 'SET_DELETE_FOLDER';

export const GET_DELETE_FILES = 'GET_DELETE_FILES';
export const SET_DELETE_FILES = 'SET_DELETE_FILES';



export const GET_CREATE_ASSIGNMENT = 'GET_CREATE_ASSIGNMENT';
export const SET_CREATE_ASSIGNMENT = 'SET_CREATE_ASSIGNMENT';

export const GET_ASSIGNMENTS = 'GET_ASSIGNMENTS';
export const SET_ASSIGNMENTS = 'SET_ASSIGNMENTS';

export const GET_ASSIGNMENT_BY_ID = 'GET_ASSIGNMENT_BY_ID';
export const SET_ASSIGNMENT_BY_ID = 'SET_ASSIGNMENT_BY_ID';


export const SET_ASSIGNMENT_ERROR = 'SET_ASSIGNMENT_ERROR';
export const SET_ASSIGNMENT_LOADING = 'SET_ASSIGNMENT_LOADING';