export const GET_MY_FILES = 'GET_MY_FILES';
export const SET_MY_FILES = 'SET_MY_FILES';

export const GET_MY_FILES_BY_ID = 'GET_MY_FILES_BY_ID';
export const SET_MY_FILES_BY_ID = 'SET_MY_FILES_BY_ID';

export const SET_ASSIGNMENT_ERROR = 'SET_ASSIGNMENT_ERROR';
export const SET_ASSIGNMENT_LOADING = 'SET_ASSIGNMENT_LOADING';