export const GET_CREATE_ASSIGNMENT = 'GET_CREATE_ASSIGNMENT';
export const SET_CREATE_ASSIGNMENT = 'SET_CREATE_ASSIGNMENT';

export const GET_ASSIGNMENTS = 'GET_ASSIGNMENTS';
export const SET_ASSIGNMENTS = 'SET_ASSIGNMENTS';

export const GET_ASSIGNMENT_BY_ID = 'GET_ASSIGNMENT_BY_ID';
export const SET_ASSIGNMENT_BY_ID = 'SET_ASSIGNMENT_BY_ID';

export const GET_COMPLETED_ASSIGNMENT = 'GET_COMPLETED_ASSIGNMENT';
export const SET_COMPLETED_ASSIGNMENT = 'SET_COMPLETED_ASSIGNMENT';

export const GET_CREATE_STUDENT_ASSIGNMENT = 'GET_CREATE_STUDENT_ASSIGNMENT';
export const SET_CREATE_STUDENT_ASSIGNMENT = 'SET_CREATE_STUDENT_ASSIGNMENT';

export const GET_STUDENT_ASSIGNMENTS = 'GET_STUDENT_ASSIGNMENTS';
export const SET_STUDENT_ASSIGNMENTS = 'SET_STUDENT_ASSIGNMENTS';


export const GET_SUBJECTS = 'GET_SUBJECTS';
export const SET_SUBJECTS = 'SET_SUBJECTS';


export const SET_ASSIGNMENT_ERROR = 'SET_ASSIGNMENT_ERROR';
export const SET_ASSIGNMENT_LOADING = 'SET_ASSIGNMENT_LOADING';