export const GET_CLASSES = 'GET_CLASSES';
export const SET_CLASSES = 'SET_CLASSES';


export const GET_CREATE_CLASS = 'GET_CREATE_CLASS';
export const SET_CREATE_CLASS = 'SET_CREATE_CLASS';


export const GET_STUDENT_GROUP = 'GET_STUDENT_GROUP';
export const SET_STUDENT_GROUP = 'SET_STUDENT_GROUP';


export const GET_CLASSES_ID = 'GET_CLASSES_ID';
export const SET_CLASSES_ID = 'SET_CLASSES_ID';


export const GET_STUDENT_GROUP_ADD = 'GET_STUDENT_GROUP_ADD';
export const SET_STUDENT_GROUP_ADD = 'SET_STUDENT_GROUP_ADD';


export const GET_CLASSES_WITH_STUDENT = 'GET_CLASSES_WITH_STUDENT';
export const SET_CLASSES_WITH_STUDENT = 'SET_CLASSES_WITH_STUDENT';


export const SET_CLASSES_ERROR = 'SET_CLASSES_ERROR';
export const SET_CLASSES_LOADING = 'SET_CLASSES_LOADING';
