export const GET_MY_FILES = 'GET_MY_FILES';
export const SET_MY_FILES = 'SET_MY_FILES';

export const GET_MY_FILES_BY_ID = 'GET_MY_FILES_BY_ID';
export const SET_MY_FILES_BY_ID = 'SET_MY_FILES_BY_ID';

export const GET_CREATE_FOLDER = 'GET_CREATE_FOLDER';
export const SET_CREATE_FOLDER = 'SET_CREATE_FOLDER';

export const GET_CREATE_FILES = 'GET_CREATE_FILES';
export const SET_CREATE_FILES = 'SET_CREATE_FILES';


export const GET_DELETE_FOLDER = 'GET_DELETE_FOLDER';
export const SET_DELETE_FOLDER = 'SET_DELETE_FOLDER';

export const GET_DELETE_FILES = 'GET_DELETE_FILES';
export const SET_DELETE_FILES = 'SET_DELETE_FILES';

export const GET_UPDATE_FOLDER = 'GET_UPDATE_FOLDER';
export const SET_UPDATE_FOLDER = 'SET_UPDATE_FOLDER';


export const GET_UPDATE_FILE = 'GET_UPDATE_FILE';
export const SET_UPDATE_FILE = 'SET_UPDATE_FILE';


export const SET_MYFILE_ERROR = 'SET_MYFILE_ERROR';
export const SET_MYFILE_LOADING = 'SET_MYFILE_LOADING';