export const GET_CREATE_STUDENT_PACKAGES = 'GET_CREATE_STUDENT_PACKAGES';
export const SET_CREATE_STUDENT_PACKAGES = 'SET_CREATE_STUDENT_PACKAGES';

export const GET_STUDENTS = 'GET_STUDENTS';
export const SET_STUDENTS = 'SET_STUDENTS';

export const GET_STUDENTS_GROUP = 'GET_STUDENTS_GROUP';
export const SET_STUDENTS_GROUP = 'SET_STUDENTS_GROUP';


export const GET_CREATE_GROUP = 'GET_CREATE_GROUP';
export const SET_CREATE_GROUP = 'SET_CREATE_GROUP';



export const GET_VALIDATE_STUDENT = 'GET_VALIDATE_STUDENT';
export const SET_VALIDATE_STUDENT = 'SET_VALIDATE_STUDENT';



export const SET_STUDENT_ERROR = 'SET_STUDENT_ERROR';
export const SET_STUDENT_LOADING = 'SET_STUDENT_LOADING';
