export const GET_STUDENTS = 'GET_STUDENTS';
export const SET_STUDENTS = 'SET_STUDENTS';

export const SET_STUDENTS_ERROR = 'SET_STUDENTS_ERROR';
export const SET_STUDENTS_LOADING = 'SET_STUDENTS_LOADING';