export const GET_CREATE_STUDENT_PACKAGES = 'GET_CREATE_STUDENT_PACKAGES';
export const SET_CREATE_STUDENT_PACKAGES = 'SET_CREATE_STUDENT_PACKAGES';

export const SET_STUDENT_ERROR = 'SET_STUDENT_ERROR';
export const SET_STUDENT_LOADING = 'SET_STUDENT_LOADING';
