export const GET_USER_LIST = 'GET_USER_LIST';
export const SET_USER_LIST = 'SET_USER_LIST';

export const GET_ON_BOARD_TUTOR = 'GET_ON_BOARD_TUTOR';
export const SET_ON_BOARD_TUTOR = 'SET_ON_BOARD_TUTOR';


export const SET_USER_ERROR = 'SET_USER_ERROR';
export const SET_USER_LOADING = 'SET_USER_LOADING';