

import { Icon } from '@iconify/react';

export const RecentClassesData = [
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    // // material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    // // material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    // material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    // material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    // material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    // material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    // material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    // material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    // material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    // material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    // material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  // Add more data as needed
];

export const RecentClassesColumns = [
  { header: 'Class Title', key: 'classTitle' },
  { header: 'Subject', key: 'subject' },
  { header: 'Student', key: 'student' },
  { header: 'Date', key: 'date' },
  { header: 'Time', key: 'time' },
  { header: 'Duration', key: 'duration' },
  { header: 'Assignment', key: 'assignment' },
//   { header: 'Material', key: 'material' },
];


//  2 data 

export const StudentsData = [
    {
        name: "Math 101",
        classes: "Mathematics",
        present: "John Doe",
        parentContact: "2024-09-07",
        absent: "10:30 AM",
        remarks: "2 hours",
    },
    {
        name: "Math 101",
        classes: "Mathematics",
        present: "John Doe",
        parentContact: "2024-09-07",
        absent: "10:30 AM",
        remarks: "2 hours",
    },
    {
        name: "Math 101",
        classes: "Mathematics",
        present: "John Doe",
        parentContact: "2024-09-07",
        absent: "10:30 AM",
        remarks: "2 hours",
    },
    {
        name: "Math 101",
        classes: "Mathematics",
        present: "John Doe",
        parentContact: "2024-09-07",
        absent: "10:30 AM",
        remarks: "2 hours",
    },
    {
        name: "Math 101",
        classes: "Mathematics",
        present: "John Doe",
        parentContact: "2024-09-07",
        absent: "10:30 AM",
        remarks: "2 hours",
    },
    {
        name: "Math 101",
        classes: "Mathematics",
        present: "John Doe",
        parentContact: "2024-09-07",
        absent: "10:30 AM",
        remarks: "2 hours",
    },
    {
        name: "Math 101",
        classes: "Mathematics",
        present: "John Doe",
        parentContact: "2024-09-07",
        absent: "10:30 AM",
        remarks: "2 hours",
    },
    {
        name: "Math 101",
        classes: "Mathematics",
        present: "John Doe",
        parentContact: "2024-09-07",
        absent: "10:30 AM",
        remarks: "2 hours",
    },
    {
        name: "Math 101",
        classes: "Mathematics",
        present: "John Doe",
        parentContact: "2024-09-07",
        absent: "10:30 AM",
        remarks: "2 hours",
    },
    {
        name: "Math 101",
        classes: "Mathematics",
        present: "John Doe",
        parentContact: "2024-09-07",
        absent: "10:30 AM",
        remarks: "2 hours",
    },
    {
        name: "Math 101",
        classes: "Mathematics",
        present: "John Doe",
        parentContact: "2024-09-07",
        absent: "10:30 AM",
        remarks: "2 hours",
    },
    // Add more data as needed
  ];
  
  export const StudentColumns = [
    { header: 'Name', key: 'name' },
    { header: 'Classes', key: 'classes' },
    { header: 'Present', key: 'present' },
    { header: 'Parent contact', key: 'parentContact' },
    { header: 'Absent', key: 'absent' },
    { header: 'Remarks', key: 'remarks' },
 ];