import '../styles/globals.css'
import StoreProvider from "./StoreProvider";

export const metadata = {
  title: 'TutorNow',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}
