import { GoogleOAuthProvider } from "@react-oauth/google";
import '../styles/globals.css'
import StoreProvider from "./StoreProvider";
import Middleware from "./middleware"

export const metadata = {
  title: 'TutorNow',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Middleware>
            {children}
          </Middleware>
        </StoreProvider>
      </body>
    </html>
  )
}
