

import { Icon } from '@iconify/react';

export const data = [
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  {
    classTitle: "Math 101",
    subject: "Mathematics",
    student: "John Doe",
    date: "2024-09-07",
    time: "10:30 AM",
    duration: "2 hours",
    assignment: "Homework 1",
    material: <Icon icon="ph:link-bold" width="18" height="18" color="gray" />,
  },
  // Add more data as needed
];

// export const columns = [
//   { header: 'Class Title', key: 'classTitle' },
//   { header: 'Subject', key: 'subject' },
//   { header: 'Student', key: 'student' },
//   { header: 'Date', key: 'date' },
//   { header: 'Time', key: 'time' },
//   { header: 'Duration', key: 'duration' },
//   { header: 'Assignment', key: 'assignment' },
//   { header: 'Material', key: 'material' },
// ];
export const columns = [
  { header: 'Class Title', key: 'classTitle' },
  { header: 'Subject', key: 'subject', dropdownOptions: ['Math', 'Science', 'History'] },
  { header: 'Student', key: 'student' },
  { header: 'Date', key: 'date' },
  { header: 'Time', key: 'time' },
  { header: 'Duration', key: 'duration' },
  { header: 'Assignment', key: 'assignment' },
  { header: 'Material', key: 'material' },
];

